### Write a NumPy program to print the NumPy version in your system.

In [3]:
import numpy as np
print(np.__version__)

1.19.2


### Vector using list

In [4]:
# Vector in Linear Algebra

a = [3, 5, -5, 8]
# This is a 4 dimensional vector
# a list in python is a vector in linear algebra

print("Vector a = ", a)
# This is how we can print a vector in python

z = [0, 0, 0, 0]
print("Zero Vector z = ", z)
# This is a zero vector

Vector a =  [3, 5, -5, 8]
Zero Vector z =  [0, 0, 0, 0]


### Defining Vector using Numpy

In [7]:
# Linear Algebra Learning Sequence
# Defining a vector using numpy

import numpy as np

# Use of np.array() to define a vector
V1 = np.array([[1],[2],[3]])
V2 = np.array([[14],[23],[35],[56],[754],[123]])

# printing vectors
print("The Vector V1 = \n",V1)
print("The Vector V2 = \n",V2)

The Vector V1 = 
 [[1]
 [2]
 [3]]
The Vector V2 = 
 [[ 14]
 [ 23]
 [ 35]
 [ 56]
 [754]
 [123]]


### Vector with User Defined Length

In [8]:
n = int(input("Enter the length of the vector you want to define: "))

v = []

for i in range(n):
    v.append(int(input('Enter the element: ')))
    
print("Vector you defined = ", v)

Enter the length of the vector you want to define: 6
Enter the element: 1
Enter the element: 2
Enter the element: 3
Enter the element: 4
Enter the element: 5
Enter the element: 6
Vector you defined =  [1, 2, 3, 4, 5, 6]


### Adding two vectors

In [9]:
#Vectors in Linear Algebra

a = [3, 5, -5, 8]
b = [4, 7, 9, -4]

print("Vector a = ", a)
print("Vector b = ", b)

# This is a 4 dimensional vector
# a list in python is a vector in linear algebra

# adding vectors
sum = []
for i in range(len(a)):
    sum.append(a[i] + b[i])

print("Vector Addition = ", sum)

Vector a =  [3, 5, -5, 8]
Vector b =  [4, 7, 9, -4]
Vector Addition =  [7, 12, 4, 4]


### Matrices

In [7]:
b = list(zip(z,c_vector))
print(b)
print("Note that the length of our zipped list is 2 not (2 by 2):",len(b))

[(5, 1), (6, 2)]
Note that the length of our zipped list is 2 not (2 by 2): 2


In [8]:
print( "But we can convert the list to a matrix like this:")
A = np.array(b)
print( A)
print( type(A))
print( "A has shape:",A.shape)

But we can convert the list to a matrix like this:
[[5 1]
 [6 2]]
<class 'numpy.ndarray'>
A has shape: (2, 2)


### Matrix Addition

In [14]:
# Program to add two matrices using nested loop
X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]

result = [[0,0,0],
        [0,0,0],
        [0,0,0]]

# iterate through rows
for i in range(len(X)):
# iterate through columns
    for j in range(len(X)):
        result[i][j] = X[i][j] + Y[i][j]

for r in result:
    print(r)

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


In [11]:
# importing numpy as np
import numpy as np


# creating first matrix
A = np.array([[1, 2], [3, 4]])

# creating second matrix
B = np.array([[4, 5], [6, 7]])

print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)

# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]


In [12]:
# importing numpy as np
import numpy as np


# creating first matrix
A = np.array([[1, 2], [3, 4]])

# creating second matrix
B = np.array([[4, 5], [6, 7]])

print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)

# subtracting two matrix
print("Subtraction of two matrix")
print(np.subtract(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Subtraction of two matrix
[[-3 -3]
 [-3 -3]]


### Take Matrix input from user 

In [13]:
# A basic code for matrix input from user

R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))

# Initialize matrix
matrix = []
print("Enter the entries rowwise:")

# For user input
for i in range(R): # A for loop for row entries
    a =[]
    for j in range(C): # A for loop for column entries
        a.append(int(input()))
    matrix.append(a)

# For printing the matrix
for i in range(R):
    for j in range(C):
        print(matrix[i][j], end = " ")
    print()

Enter the number of rows:2
Enter the number of columns:3
Enter the entries rowwise:
1
2
3
3
3
3
1 2 3 
3 3 3 


### multiply two matrices

In [ ]:
# Program to multiply two matrices using nested loops

# take a 3x3 matrix
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]

# take a 3x4 matrix
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]
    
result = [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]

# iterating by row of A
for i in range(len(A)):

    # iterating by column by B
    for j in range(len(B[0])):

        # iterating by rows of B
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]

for r in result:
    print(r)
